accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mysite import views
from articles import views as articles_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', articles_views.article_list, name='homepage'),
    path('about/', views.about, name ='about'),
    path('articles/', include('articles.ulrs')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.contrib.auth.models import User
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(upload_to='images/', blank=True, default='images/default.jpg' )
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[0:50] + '...'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UsernameField
from django.contrib.auth import password_validation

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"autofocus": True, "class":"form-control mb-3"}))
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "currect-password", "class":"form-control mb-3"}),
    )

class SignupForm(UserCreationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"autofocus": True, "class": "form-control mb-3"}))
    password1 = forms.CharField(
        label="Password",
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "currect-password", "class": "form-control mb-3"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label="Password",
        required= True,
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "currect-password", "class": "form-control mb-3"}),
        help_text="Enter the same password as before, for verification",
    )

articles/forms.py
from django import forms

from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'thumbnail']
        labels = {
            "title": "Title",
            "body": "Text",
            "thumbnail": "Thumbnail"
        }
        widgets = {
            "title": forms.TextInput(attrs={'placeholder': 'Write article title', 'class': 'form-control mb-3'}),
            "body": forms.TextInput(attrs={'placeholder': 'Write article text', 'class': 'form-control mb-3'}),
            "thumbnail": forms.FileInput(attrs={'class': 'form-control mb-3'}),
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from accounts.forms import LoginForm, SignupForm


def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect('/articles')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('/articles')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
    return HttpResponseRedirect('/articles')

articles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from articles.models import Article
from . import forms
from django.http import HttpResponse


def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'article_list.html', {'articles': articles})


def article_item(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'article_item.html', {'article': article})


@login_required(login_url='accounts:login')
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('homepage')
    else:
        form = forms.CreateArticle()


@login_required(login_url='accounts:login')
def article_update(request, slug):
    article = Article.objects.get(slug=slug)
    if request.user.id == article.author.id:
        form = forms.CreateArticle(request.POST, request.FILES, instance=article)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:article_detail', slug=article.slug)
        else:
            form = forms.CreateArticle(instance=article)
        return render(request, 'article_form.html', {'form': form})
    return HttpResponse('401 Unauthorized', status=401)


@login_required(login_url='accounts:login')
def article_delete(request, slug):
    article = Article.objects.get(slug=slug)
    if request.user.id == article.author.id:
        if request.method == 'POST':
            article.delete()
            return redirect('homepage')
        return render(request, 'article_delete.html', {'article': article})
    return HttpResponse('401 Unathorized', status=401)

mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
    data = {'header': 'Homepage', "message": "message welcome"}
    return render(request, "article_item.html", data)


def about(request):
    header = "About us"
    staff = ['John', "Lorem", 'Anoter Lorem']
    director = {"name": "some_name", "img": "/director.jpg"}
    adress = ('20', 'some city', 'befor', 'e')
    data = {"header": header, "staff": staff, "director": director, "address": adress}
    return render(request, 'about.html', data)

accounts/templates/login.html
{% extends "base_layot.html" %}
{% load static %}
{% block title %} Article Form {% endblock title %}
{% block content %}
<main>
    <h1>Login</h1>
    <form class="form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <button type="submit">Login</button>
    </form>
</main>
{% endblock content %}

accounts/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

accounts/templates/signup.html
{% extends "base_layot.html" %}
{% load static %}
{% block title %} Article Form {% endblock title %}
{% block content %}
<main>
    <h1>SIGHUP</h1>
    <form class="form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit">Sign up</button>
    </form>
</main>
{% endblock content %}

articles/templates/article_create.html
{% extends "base_layot.html" %}
{% load static %}
{% block title %} Create article {% endblock title %}
{% block content %}
<main>
<h1>Create article</h1>
<form class="form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <button type="submit">Create article</button>
</form>
</main>
{% endblock content %}

articles/templates/article_delete.html
{% extends "base_layot.html" %}
{% load static %}
{% block title %} {{article.title}} {% endblock title %}
{% block content %}
<main>
<h1>Are u sure?</h1>
<form class="form" method="post">
    {% csrf_token %}
    <button type="submit" class ="btn btn-danger">Yes</button>
    <a href="{% url 'homepage' %}" class="btn btn-secondary">Cancel</a>
</form>
</main>
{% endblock content %}

articles/templates/article_form.html
{% extends "base_layot.html" %}
{% load static %}
{% block title %} Article Form {% endblock title %}
{% block content %}
<main>
<h1>Article Form</h1>
<form class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>
</form>
</main>
{% endblock content %}

articles/templates/article_item.html
{% extends "base_layot.html" %}
{% block  title %}{{article.title}}{% endblock title %}
{% block content %}
<div class = "article-detail">
    <img src="{{article.thumbnail.url}}" alt="" class="article-image">
    <h1>{{ article.title}}</h1>
    <p>{{ article.body}}</p>
    {% if user.is_authenticated and user.id == article.author.id %}
    <div>
        <a class="btn btn-warning" href="{% url 'articles:update' slug=article.slug %}">
            Update
        </a>
        <a class="btn btn-danger" href="{% url 'articles:delete' slug=article.slug %}">
            Delete
        </a>
    </div>
    {% endif %}
</div>
{% endblock content %}

articles/templates/article_list.html
{% extends "base_layot.html" %}
{% block  title %}{{article.title}}{% endblock title %}
{% block content %}
<main>
    <h1>Article List</h1>
    <div class="articles">
        {% for element in articles %}
        <div class="article_item">
            <h2>
                <a href="{% url 'articles:article_detail' slug=element.slug %}">
                    {{ element.title }}
                </a>
            </h2>
            <p>
                {{element.snippet}}
            </p>
            <time>
                {{ element.date}}
            </time>
        </div>
        {% endfor %}
        {% if user.is_authenticated %}
        <div><a href="{% url 'articles:create'%}"><button type="submit" class="create"> create article</button></a></div>
        {% else %}
        {% endif %}
    </div>
</main>
{% endblock content %}

articles/templates/base_layot.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %}Default title{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<header class="header">
    <div class="container">
        <div class="logo">
        </div>
        <nav class="nav">
            <ul class="nav-list">
                {% if user.is_authenticated %}
                <li>
                    <form class="form" action="/accounts/logout/" method="post">
                        {% csrf_token %}
                        <button type="submit" class="logout">Logout</button>
                    </form>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
                </li>
                <li>
                    <a href="{% url 'accounts:signup' %}" class="nav-link">Sign up</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a href="{% url 'homepage' %}" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'homepage' %}" class="nav-link">Articles</a>
                </li>
            </ul>
        </nav>
    </div>
</header>
{% block content %} {% endblock content %}
</body>
<html>